### ISSUE TITLE
Multiple formatting errors

### ISSUE THREAD

**Issue by ElSaico** [MicrosoftDocs/winapps-winrt-api#108]
Hello,

I'm working on a parser tool to autogenerate pages for the PyWinRT documentation, and a handful of files deviated from the expected structure - which tends to show up as errors on the website:

**Source:** `microsoft.ui.composition\compositor_creategeometricclip_1810234015.md`
https://learn.microsoft.com/en-us/windows/windows-app-sdk/api/winrt/microsoft.ui.composition.compositor.creategeometricclip
The first overload has a `<h1>` header in the middle of the Returns section.

**Source:** `microsoft.ui.xaml.automation.peers\tabviewitemautomationpeer_tabviewitemautomationpeer_467232663.md`
https://learn.microsoft.com/en-us/windows/windows-app-sdk/api/winrt/microsoft.ui.xaml.automation.peers.tabviewitemautomationpeer.-ctor
The source file lacks a `-description` header, and thus its description is not rendered.

**Source:** `microsoft.ui.xaml.controls\datatemplateselector_selecttemplatecore_83003154.md`
https://learn.microsoft.com/en-us/windows/windows-app-sdk/api/winrt/microsoft.ui.xaml.controls.datatemplateselector.selecttemplatecore
The second overload has a deprecation notice on its source file that is not rendered.

**Source:** `microsoft.ui.xaml.controls\layoutcontext_layoutstate.md`
https://learn.microsoft.com/en-us/windows/windows-app-sdk/api/winrt/microsoft.ui.xaml.controls.layoutcontext.layoutstate
Duplicated level 1 header in the source file - not reflected on the output.

**Source:** `microsoft.ui.xaml.controls.primitives\columnmajoruniformtolargestgridlayout_rowspacingproperty.md`
https://learn.microsoft.com/en-us/windows/windows-app-sdk/api/winrt/microsoft.ui.xaml.controls.primitives.columnmajoruniformtolargestgridlayout.rowspacingproperty
The source file lacks a `-description` header, and thus its description is not rendered.

**Source:** `microsoft.windows.widgets\microsoft_windows_widgets.md`
https://learn.microsoft.com/en-us/windows/windows-app-sdk/api/winrt/microsoft.windows.widgets
The `-description` header is out of place in the source file (yet somehow renders correctly...).

**Comment by jwmsft** [comment]
Thanks for reporting these issues. They have been corrected.
