### ISSUE TITLE
Wrong screenshot of Mouse Properties "Wheel" tab

### ISSUE THREAD

**Issue by DJm00n** [MicrosoftDocs/winapps-winrt-api#14]
1. [microsoft.ui.input/mousewheelparameters_chartranslation.md](https://github.com/MicrosoftDocs/winapps-winrt-api/blob/972aa8f334b1b4552bf4bbc0e939f82583698503/microsoft.ui.input/mousewheelparameters_chartranslation.md)
2. [microsoft.ui.input/mousewheelparameters_pagetranslation.md](https://github.com/MicrosoftDocs/winapps-winrt-api/blob/972aa8f334b1b4552bf4bbc0e939f82583698503/microsoft.ui.input/mousewheelparameters_pagetranslation.md)

These two pages contains wrong screenshot that shows "Pointer options" tab instead of "Wheel" tab:
![image](https://github.com/MicrosoftDocs/winapps-winrt-api/raw/972aa8f334b1b4552bf4bbc0e939f82583698503/microsoft.ui.input/images/MouseProperties_ButtonWheel.png)

Please update screenshot with proper one.

**Comment by DJm00n** [comment]
Here is proper screenshot from Windows 11:

![image](https://user-images.githubusercontent.com/1285934/220346176-1e62e618-10bb-4832-b295-3ce9a26e6858.png)

**Comment by Karl-Bridge-Microsoft** [comment]
Image has been updated in both the UWP WinRT API docs and the WinApp SDK WinRT docs. Thanks!
