### ISSUE TITLE
just a typo?

### ISSUE THREAD

**Issue by vmx17** [MicrosoftDocs/winapps-winrt-api#15]
In the head of sample code, there is;<br>
`Windows.UI.Xaml.Input.Pointer ptr = e.Pointer;`<br>
Is this correct for WindowsAppSDK1.2? (not `Microsoft.UI....`?)
and in my VisualStudio, the `Windows.UI.Xaml.Input` is shown as `CS0234The type or namespace 'Input' does not exist in the namespace 'Windows.UI.Xaml' ...`.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1492dd7c-cb14-70e7-90a2-c32b832e5215
* Version Independent ID: 1492dd7c-cb14-70e7-90a2-c32b832e5215
* Content: [UIElement.PointerReleased Event (Microsoft.UI.Xaml) - Windows App SDK](https://learn.microsoft.com/en-us/windows/windows-app-sdk/api/winrt/microsoft.ui.xaml.uielement.pointerreleased?view=windows-app-sdk-1.2)
* Content Source: [winapps-winrt-build/xml/Microsoft.UI.Xaml/UIElement.xml](https://github.com/MicrosoftDocs/winapps-winrt-api/blob/docs/winapps-winrt-build/xml/Microsoft.UI.Xaml/UIElement.xml)
* Product: **reunion**
* Technology: **reunion-reference**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by Karl-Bridge-Microsoft** [comment]
@vmx17 - thanks for pointing this out! A fix should be live shortly.
