### ISSUE TITLE
SetIcon iconPath parameter must be a path to an ICO file

### ISSUE THREAD

**Issue by MikeHillberg** [MicrosoftDocs/winapps-winrt-api#19]
The AppWindow.SetIcon(string) doesn't call out the restriction that the string must be a path to an ICO file, as is [described here](https://learn.microsoft.com/en-us/windows/apps/develop/title-bar?tabs=wasdk#icon-and-system-menu).

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ee69a7f6-f74a-daf1-bde5-ea9961f6988f
* Version Independent ID: 16d39b63-659a-5f58-5880-a56cb841cba5
* Content: [AppWindow.SetIcon Method (Microsoft.UI.Windowing) - Windows App SDK](https://learn.microsoft.com/en-us/windows/windows-app-sdk/api/winrt/Microsoft.UI.Windowing.AppWindow.SetIcon?view=windows-app-sdk-1.2)
* Content Source: [winapps-winrt-build/xml/Microsoft.UI.Windowing/AppWindow.xml](https://github.com/MicrosoftDocs/winapps-winrt-api/blob/docs/winapps-winrt-build/xml/Microsoft.UI.Windowing/AppWindow.xml)
* Product: **reunion**
* Technology: **reunion-reference**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by jwmsft** [comment]
Thanks for the feedback. The SetIcon doc has been updated with the information from the Title bar doc.
