### ISSUE TITLE
Bad reference

### ISSUE THREAD

**Issue by MikeHillberg** [MicrosoftDocs/winapps-winrt-api#22]
There's a reference that isn't getting resolved and so is showing up in the raw xref format:

<xref:Microsoft.Windows.Widgets.Providers.IWidgetProvider.CreateWidget(Microsoft.Windows.Widgets.Providers.WidgetContext>

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e72a0d36-d722-ed31-54fe-1d5ea6a979b7
* Version Independent ID: e72a0d36-d722-ed31-54fe-1d5ea6a979b7
* Content: [IWidgetProvider.Activate(WidgetContext) Method (Microsoft.Windows.Widgets.Providers) - Windows App SDK](https://learn.microsoft.com/en-us/windows/windows-app-sdk/api/winrt/Microsoft.Windows.Widgets.Providers.IWidgetProvider.Activate?view=windows-app-sdk-1.2)
* Content Source: [winapps-winrt-build/xml/Microsoft.Windows.Widgets.Providers/IWidgetProvider.xml](https://github.com/MicrosoftDocs/winapps-winrt-api/blob/docs/winapps-winrt-build/xml/Microsoft.Windows.Widgets.Providers/IWidgetProvider.xml)
* Product: **reunion**
* Technology: **reunion-reference**
* GitHub Login: @GrantMeStrength
* Microsoft Alias: **jken**

**Comment by jwmsft** [comment]
Thanks for reporting this. The link is fixed.
