### ISSUE TITLE
Invalid statement related to creating ResourceDictionaries with Visual Studio

### ISSUE THREAD

**Issue by kmgallahan** [MicrosoftDocs/winapps-winrt-api#27]
This statement:

> You can use Microsoft Visual Studio to create resource dictionaries. This example was created with these steps: put a [TextBlock](https://learn.microsoft.com/en-us/windows/windows-app-sdk/api/winrt/microsoft.ui.xaml.controls.textblock?view=windows-app-sdk-1.2) on the design surface, right click, choose Edit Style / Create Empty, then "This document" to define the new resource in Page.Resources.

is invalid because there is no designer to use in VS when using WASDK / WinUI 3.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: cdd47ea5-e60e-2794-e4fd-13a54a983193
* Version Independent ID: cdd47ea5-e60e-2794-e4fd-13a54a983193
* Content: [ResourceDictionary Class (Microsoft.UI.Xaml) - Windows App SDK](https://learn.microsoft.com/en-us/windows/windows-app-sdk/api/winrt/microsoft.ui.xaml.resourcedictionary?f1url=%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(Microsoft.UI.Xaml.ResourceDictionary)%3Bk(VS.XamlEditor)%26rd%3Dtrue&view=windows-app-sdk-1.2)
* Content Source: [winapps-winrt-build/xml/Microsoft.UI.Xaml/ResourceDictionary.xml](https://github.com/MicrosoftDocs/winapps-winrt-api/blob/docs/winapps-winrt-build/xml/Microsoft.UI.Xaml/ResourceDictionary.xml)
* Product: **reunion**
* Technology: **reunion-reference**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by jwmsft** [comment]
Thanks for opening this issue. The page has been updated.
