### ISSUE TITLE
See also section is broken

### ISSUE THREAD

**Issue by kmgallahan** [MicrosoftDocs/winapps-winrt-api#28]
The 'See also' section on this page is broken. It reads:

`<xref:Microsoft.UI.Xaml.Controls.Control%0a+-see-also%0aT%3aMicrosoft.UI.Xaml.Controls.Control>`

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7317562a-87de-eb17-f071-79feead5616f
* Version Independent ID: 7317562a-87de-eb17-f071-79feead5616f
* Content: [UserControl Class (Microsoft.UI.Xaml.Controls) - Windows App SDK](https://learn.microsoft.com/en-us/windows/windows-app-sdk/api/winrt/microsoft.ui.xaml.controls.usercontrol?f1url=%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(Microsoft.UI.Xaml.Controls.UserControl)%3Bk(VS.XamlEditor)%26rd%3Dtrue&view=windows-app-sdk-1.2)
* Content Source: [winapps-winrt-build/xml/Microsoft.UI.Xaml.Controls/UserControl.xml](https://github.com/MicrosoftDocs/winapps-winrt-api/blob/docs/winapps-winrt-build/xml/Microsoft.UI.Xaml.Controls/UserControl.xml)
* Product: **reunion**
* Technology: **reunion-reference**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by jwmsft** [comment]
Thanks for opening this issue. The page has been updated.
