### ISSUE TITLE
Documentation pages C# examples referencing the wrong (old?) assembly

### ISSUE THREAD

**Issue by brmykleb** [MicrosoftDocs/winapps-winrt-api#3]
Hi,

When trying to set Fontwheight in codebehind on a RichTextBlock, I noticed that the c# examples in your documentation are referencing a non-existent assembly. For someone that has not been working with the Windows App SDK for long, this is confusing and slows down development pace. 
I noticed this on two of the pages, but I suspect there are more.
https://learn.microsoft.com/en-us/windows/windows-app-sdk/api/winrt/microsoft.ui.xaml.controls.richtextblock?view=windows-app-sdk-1.1
https://learn.microsoft.com/en-us/windows/windows-app-sdk/api/winrt/microsoft.ui.text.fontweights?view=windows-app-sdk-1.1
Although the correct namespace is listed several places on the page, the example uses a wrong (old) one:

textBlock1.FontWeight = Windows.UI.Text.FontWeights.ExtraBlack;
should be:
textBlock1.FontWeight = Microsoft.UI.Text.FontWeights.ExtraBlack; 

Best regards,
Torgeir

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e750e3d0-fe2d-30c2-a8a3-b8a1f99cbd07
* Version Independent ID: e750e3d0-fe2d-30c2-a8a3-b8a1f99cbd07
* Content: [FontWeights Class (Microsoft.UI.Text) - Windows App SDK](https://learn.microsoft.com/en-us/windows/windows-app-sdk/api/winrt/microsoft.ui.text.fontweights?view=windows-app-sdk-1.1)
* Content Source: [winapps-winrt-build/xml/Microsoft.UI.Text/FontWeights.xml](https://github.com/MicrosoftDocs/winapps-winrt-api/blob/docs/winapps-winrt-build/xml/Microsoft.UI.Text/FontWeights.xml)
* Product: **reunion**
* Technology: **reunion-reference**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by jwmsft** [comment]
Thanks for letting us know about this error. A PR has been submitted to update these docs, and we'll check for this issue in other docs.
