### ISSUE TITLE
XamlMarkupHelper.UnloadObject should reference x:Load

### ISSUE THREAD

**Issue by MikeHillberg** [MicrosoftDocs/winapps-winrt-api#4]
This API exists to unload an object that was loaded by [x:Load](https://learn.microsoft.com/en-us/windows/uwp/xaml-platform/x-load-attribute), it should have a reference to that page.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0ca78730-03a5-4fbc-89db-424155c526f6
* Version Independent ID: 0ca78730-03a5-4fbc-89db-424155c526f6
* Content: [XamlMarkupHelper.UnloadObject(DependencyObject) Method (Microsoft.UI.Xaml.Markup) - Windows App SDK](https://learn.microsoft.com/en-us/windows/windows-app-sdk/api/winrt/Microsoft.UI.Xaml.Markup.XamlMarkupHelper.UnloadObject?view=windows-app-sdk-1.1)
* Content Source: [winapps-winrt-build/xml/Microsoft.UI.Xaml.Markup/XamlMarkupHelper.xml](https://github.com/MicrosoftDocs/winapps-winrt-api/blob/docs/winapps-winrt-build/xml/Microsoft.UI.Xaml.Markup/XamlMarkupHelper.xml)
* Product: **reunion**
* Technology: **reunion-reference**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by jwmsft** [comment]
Thanks @MikeHillberg. A PR has been submitted to add this information with a link to x:Load.
