### ISSUE TITLE
Analyze Microsoft.UI.Xaml.Input Pointer-related classes and members for accuracy

### ISSUE THREAD

**Issue by Karl-Bridge-Microsoft** [MicrosoftDocs/winapps-winrt-api#44]
Specific topics to analyze (but feel free to navigate to related topics not listed here and also provide feedback on those):

## Pointer Class
Pointer Class: https://learn.microsoft.com/en-us/windows/windows-app-sdk/api/winrt/microsoft.ui.xaml.input.pointer
### Members
Pointer.IsInContact Property: https://learn.microsoft.com/en-us/windows/windows-app-sdk/api/winrt/microsoft.ui.xaml.input.pointer.isincontact
Pointer.IsInRange Property: https://learn.microsoft.com/en-us/windows/windows-app-sdk/api/winrt/microsoft.ui.xaml.input.pointer.isinrange
Pointer.PointerDeviceType Property: https://learn.microsoft.com/en-us/windows/windows-app-sdk/api/winrt/microsoft.ui.xaml.input.pointer.pointerdevicetype
Pointer.PointerId Property: https://learn.microsoft.com/en-us/windows/windows-app-sdk/api/winrt/microsoft.ui.xaml.input.pointer.pointerid

## PointerEventHandler Delegate
https://learn.microsoft.com/en-us/windows/windows-app-sdk/api/winrt/microsoft.ui.xaml.input.pointereventhandler

## PointerRoutedEventArgs Class
PointerRoutedEventArgs Class:https://learn.microsoft.com/en-us/windows/windows-app-sdk/api/winrt/microsoft.ui.xaml.input.pointerroutedeventargs
### Members
PointerRoutedEventArgs.Handled Property: https://learn.microsoft.com/en-us/windows/windows-app-sdk/api/winrt/microsoft.ui.xaml.input.pointerroutedeventargs.handled
PointerRoutedEventArgs.IsGenerated Property: https://learn.microsoft.com/en-us/windows/windows-app-sdk/api/winrt/microsoft.ui.xaml.input.pointerroutedeventargs.isgenerated
PointerRoutedEventArgs.KeyModifiers Property: https://learn.microsoft.com/en-us/windows/windows-app-sdk/api/winrt/microsoft.ui.xaml.input.pointerroutedeventargs.keymodifiers
PointerRoutedEventArgs.Pointer Property:https://learn.microsoft.com/en-us/windows/windows-app-sdk/api/winrt/microsoft.ui.xaml.input.pointerroutedeventargs.pointer
PointerRoutedEventArgs.GetCurrentPoint(UIElement) Method: https://learn.microsoft.com/en-us/windows/windows-app-sdk/api/winrt/microsoft.ui.xaml.input.pointerroutedeventargs.getcurrentpoint
PointerRoutedEventArgs.GetIntermediatePoints(UIElement) Method: https://learn.microsoft.com/en-us/windows/windows-app-sdk/api/winrt/microsoft.ui.xaml.input.pointerroutedeventargs.getintermediatepoints

## What to look for:

Statements/examples that were appropriate for UWP/WinUI 2, but are no longer accurate for WinUI 3/Windows App SDK
Code examples/snippets that are not appropriate for WinUI3/Windows App SDK
Missing or incorrect detail/guidance
Identify where code examples/snippets would be helpful
Unnecessary/invalid links to UWP docs
Unnecessary/invalid links to WinUI 2 docs
References to UWP or WinUI 2
Mentions of Windows 8/8.1, whether they may need to be removed or just updated to be relevant for Win 10/11
Mentions of Windows Phone
Windows 10 is specified but it feels like Windows 11 is also applicable. (The text should either just specify "Windows" or "Windows 10 build xxxx and later" instead)

**Comment by alvinashcraft** [comment]
Closing issue from MVP Summit activity.
