### ISSUE TITLE
Analyze Microsoft.UI.Xaml.UIElement properties for accuracy (K thru L)

### ISSUE THREAD

**Issue by alvinashcraft** [MicrosoftDocs/winapps-winrt-api#48]
All property content files in UIElement beginning with:

KeyboardAcceleratorPlacementMode: https://learn.microsoft.com/windows/windows-app-sdk/api/winrt/microsoft.ui.xaml.uielement.keyboardacceleratorplacementmode

And ending with:

LosingFocusEvent: https://learn.microsoft.com/windows/windows-app-sdk/api/winrt/microsoft.ui.xaml.uielement.losingfocusevent

What to look for:

- Statements/code that were appropriate for UWP/WinUI 2, but are no longer accurate for WinUI 3/Windows App SDK
- APIs that need more explanation or samples. Content for some properties is intentionally brief, as examples are available in other topics
- Unnecessary/invalid links to UWP docs
- Unnecessary/invalid links to WinUI 2 docs
- References to UWP or WinUI 2
- Mentions of Windows 8/8.1, whether they may need to be removed or just updated to be relevant for Win 10/11
- Mentions of Windows Phone
- Windows 10 is specified but it feels like Windows 11 is also applicable. (The text should either just specify "Windows" or "Windows 10 build xxxx and later" instead)

**Comment by lukemurraynz** [comment]
I can pick this up.

**Comment by lukemurraynz** [comment]
@alvinashcraft - After PRs are approved - I believe this Issue can be closed. Let me know your thoughts.

**Comment by alvinashcraft** [comment]
@lukemurraynz I think so. I'll assign it to myself as well. Once everything is merged, I'll come back and close this one. Thanks again for your help!

**Comment by alvinashcraft** [comment]
Closing this, as the related PRs are either closed or in review. Thanks for your help yesterday!
