### ISSUE TITLE
Docs on how to find the correct generic.xaml file for WinUI are currently not correct

### ISSUE THREAD

**Issue by PureWeen** [MicrosoftDocs/winapps-winrt-api#5]
The docs here
https://learn.microsoft.com/en-us/windows/windows-app-sdk/api/winrt/microsoft.ui.xaml.controls.calendardatepicker?view=windows-app-sdk-1.2#control-style-and-template

Still reference the `UAP` generic.xaml file location

> For design purposes, generic.xaml is available in the (Program Files)\Windows Kits\10\DesignTime\CommonConfiguration\Neutral\UAP\ <SDK version>\Generic

This needs to be updated to indicate that the file is now stored alongside the nuget

`C:\Users\<user>\.nuget\packages\microsoft.windowsappsdk\1.2.220909.2-experimental2\lib\net5.0-windows10.0.18362.0\Microsoft.WinUI\Themes`

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3bacf462-acbe-5493-cb9d-aacd16dc5eba
* Version Independent ID: 3bacf462-acbe-5493-cb9d-aacd16dc5eba
* Content: [CalendarDatePicker Class (Microsoft.UI.Xaml.Controls) - Windows App SDK](https://learn.microsoft.com/en-us/windows/windows-app-sdk/api/winrt/microsoft.ui.xaml.controls.calendardatepicker?view=windows-app-sdk-1.2#control-style-and-template)
* Content Source: [winapps-winrt-build/xml/Microsoft.UI.Xaml.Controls/CalendarDatePicker.xml](https://github.com/MicrosoftDocs/winapps-winrt-api/blob/docs/winapps-winrt-build/xml/Microsoft.UI.Xaml.Controls/CalendarDatePicker.xml)
* Product: **reunion**
* Technology: **reunion-reference**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by jwmsft** [comment]
Thanks for reporting this. The docs were updated some time ago, but this issue didn't get closed then.
