### ISSUE TITLE
Windows Phone Hub Ui is mentioned.

### ISSUE THREAD

**Issue by KoprowskiT** [MicrosoftDocs/winapps-winrt-api#50]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ded27a33-63af-5bad-beb4-dbc85d34d87d
* Version Independent ID: ded27a33-63af-5bad-beb4-dbc85d34d87d
* Content: [CompositionAnimation.SetReferenceParameter(String, CompositionObject) Method (Microsoft.UI.Composition) - Windows App SDK](https://learn.microsoft.com/en-au/windows/windows-app-sdk/api/winrt/microsoft.ui.composition.compositionanimation.setreferenceparameter?view=windows-app-sdk-1.2)
* Content Source: [winapps-winrt-build/xml/Microsoft.UI.Composition/CompositionAnimation.xml](https://github.com/MicrosoftDocs/winapps-winrt-api/blob/docs/winapps-winrt-build/xml/Microsoft.UI.Composition/CompositionAnimation.xml)
* Product: **reunion**
* Technology: **reunion-reference**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by KoprowskiT** [comment]
In the examples, there is a statement: 
"This type of animation can be seen on the Windows Start Screen and Windows Phone Hub UIs." PAGE

**Comment by alvinashcraft** [comment]
Issue fixed in linked PR. Thanks, @KoprowskiT!
