### ISSUE TITLE
Search isn't working

### ISSUE THREAD

**Issue by kmgallahan** [MicrosoftDocs/winapps-winrt-api#6]
Is it me, or does the search function appear to be mostly useless?

![Screenshot 2022-10-21 062731](https://user-images.githubusercontent.com/5379488/197175051-aac7ab79-bb81-4629-bb39-cd1c257332c8.jpg)

**Comment by Karl-Bridge-Microsoft** [comment]
Thanks for letting us know. I see the same thing. I've informed the learn docs engineering team.

Closing as it's not a specific doc issue.

**Comment by Saharsh979** [comment]
Was this issue fixed? the search doesn't seem to work for me sometimes. I know the result is there, but it doesn't return anything.

**Comment by Karl-Bridge-Microsoft** [comment]
This bug is in the hands of our engineering team.
