### ISSUE TITLE
Article hasn't been updated to properly show setting XamlRoot

### ISSUE THREAD

**Issue by michael-hawker** [MicrosoftDocs/winapps-winrt-api#72]
AFAIK XamlRoot still needs to be set in WASDK/WinUI 3.

This is missing from the top/most examples, there's a call out later, but makes it seem like a special case (which it is in UWP for targeting older OS versions).

This causes confusion: https://mastodonapp.uk/@JMBragg/110736998327326561

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5a6b269b-5edd-18e3-6291-98797736f074
* Version Independent ID: 5a6b269b-5edd-18e3-6291-98797736f074
* Content: [ContentDialog Class (Microsoft.UI.Xaml.Controls) - Windows App SDK](https://learn.microsoft.com/en-gb/windows/windows-app-sdk/api/winrt/microsoft.ui.xaml.controls.contentdialog?view=windows-app-sdk-1.3)
* Content Source: [winapps-winrt-build/xml/Microsoft.UI.Xaml.Controls/ContentDialog.xml](https://github.com/MicrosoftDocs/winapps-winrt-api/blob/docs/winapps-winrt-build/xml/Microsoft.UI.Xaml.Controls/ContentDialog.xml)
* Product: **reunion**
* Technology: **reunion-reference**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by jwmsft** [comment]
@michael-hawker, thanks for catching this. The article has been updated.
