### ISSUE TITLE
TextBlock.Text nullability

### ISSUE THREAD

**Issue by weitzhandler** [MicrosoftDocs/winapps-winrt-api#74]
Does this property allow setting it to `null`?

If yes, why isn't the property value `string?`, otherwise - is an exception thrown? This should be clearly documented.

I guess same applies for `TextBox.Text`

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 25a0a900-0d6a-a656-3d34-f88b310cb6c5
* Version Independent ID: 25a0a900-0d6a-a656-3d34-f88b310cb6c5
* Content: [TextBlock.Text Property (Microsoft.UI.Xaml.Controls) - Windows App SDK](https://learn.microsoft.com/en-us/windows/windows-app-sdk/api/winrt/microsoft.ui.xaml.controls.textblock.text?view=windows-app-sdk-1.3#microsoft-ui-xaml-controls-textblock-text)
* Content Source: [winapps-winrt-build/xml/Microsoft.UI.Xaml.Controls/TextBlock.xml](https://github.com/MicrosoftDocs/winapps-winrt-api/blob/docs/winapps-winrt-build/xml/Microsoft.UI.Xaml.Controls/TextBlock.xml)
* Product: **reunion**
* Technology: **reunion-reference**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by jwmsft** [comment]
Docs have been updated with this:
"This property is not nullable. However, if you set this property to `null` (`TextBlock1.Text = null;`) no exception is thrown. Instead, it is automatically set to an empty string ("")."
