### ISSUE TITLE
What about the rest of the activation kinds? there is a lot more than 3

### ISSUE THREAD

**Issue by KWodarczyk** [MicrosoftDocs/winapps-winrt-api#76]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 48c16388-7620-4e40-8cf9-fd1157af7a77
* Version Independent ID: 03be4303-f85f-52b8-351f-2bfd357990c7
* Content: [AppActivationArguments.Data Property (Microsoft.Windows.AppLifecycle) - Windows App SDK](https://learn.microsoft.com/en-us/windows/windows-app-sdk/api/winrt/microsoft.windows.applifecycle.appactivationarguments.data?view=windows-app-sdk-1.3#microsoft-windows-applifecycle-appactivationarguments-data)
* Content Source: [winapps-winrt-build/xml/Microsoft.Windows.AppLifecycle/AppActivationArguments.xml](https://github.com/MicrosoftDocs/winapps-winrt-api/blob/docs/winapps-winrt-build/xml/Microsoft.Windows.AppLifecycle/AppActivationArguments.xml)
* Product: **reunion**
* Technology: **reunion-reference**
* GitHub Login: @alvinashcraft
* Microsoft Alias: **aashcraft**

**Comment by alvinashcraft** [comment]
Hi @KWodarczyk. That's a great question. I'm sorry for the delay in replying. I'm trying to track down someone on the product team who can help get an answer so we can improve the docs for this API. I'll keep you updated on my findings.

**Comment by alvinashcraft** [comment]
`Launch` was missing. I added that and also added a note that those are the only four kinds currently supported by Windows App SDK here. The changes should be live later today.
