### ISSUE TITLE
ICompositionSupportsSystemBackdrop.SystemBackdrop() link error of CompositionBrush

### ISSUE THREAD

**Issue by Bobby-Ling** [MicrosoftDocs/winapps-winrt-api#88]
When I tryied using code like 
```C++
myICompositionSupportsSystemBackdrop.SystemBackdrop(myCompositionBackdropBrush) 
```
, VS2022 just says 
```
E0304 No instance of overloaded function "winrt::Microsoft::UI::Composition::ICompositionSupportsSystemBackdrop::SystemBackdrop" 
```
I have created a new winUI3 C++ project using Windows App SDK 1.4.2, cpp/winrt version 2.0.220929.3, and included no header files other than those provided in `pch.h`.

Code behind works fine in C#:
```C#
public static void SetTransparent(Window window)
{
    var brushHolder = window.As<ICompositionSupportsSystemBackdrop>();
    var colorBrush = WindowsCompositionHelper.Compositor.CreateColorBrush(Windows.UI.Color.FromArgb(0, 255, 255, 255));
    brushHolder.SystemBackdrop = colorBrush;
}
```
---

#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 41d04c2d-5b65-44d2-3eb4-3471853e2e5c
* Version Independent ID: 41d04c2d-5b65-44d2-3eb4-3471853e2e5c
* Content: [ICompositionSupportsSystemBackdrop.SystemBackdrop Property (Microsoft.UI.Composition) - Windows App SDK](https://learn.microsoft.com/en-us/windows/windows-app-sdk/api/winrt/microsoft.ui.composition.icompositionsupportssystembackdrop.systembackdrop?view=windows-app-sdk-1.4)
* Content Source: [winapps-winrt-build/xml/Microsoft.UI.Composition/ICompositionSupportsSystemBackdrop.xml](https://github.com/MicrosoftDocs/winapps-winrt-api/blob/docs/winapps-winrt-build/xml/Microsoft.UI.Composition/ICompositionSupportsSystemBackdrop.xml)
* Product: **reunion**
* Technology: **reunion-reference**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by Bobby-Ling** [comment]
Thanks to [DarranRowe](https://github.com/DarranRowe)'s answer (see [Issue in microsoft-ui-xaml repo](https://github.com/microsoft/microsoft-ui-xaml/issues/9041#issuecomment-1790752268) ! He found that it was a link **mistake** of the documention. The parameter of SystemBackdrop should be **Windows**.UI.Composition.CompositionBrush, not **Microsoft**.UI.Composition.CompositionBrush. Hope it helps!

**Comment by jwmsft** [comment]
@Bobby-Ling, thanks for opening this issue. The incorrect links to CompositionBrush have been fixed.
