### ISSUE TITLE
ItemsChangedEventArgs link is broken

### ISSUE THREAD

**Issue by terrycox** [MicrosoftDocs/winapps-winrt-api#9]
Clicking the referenced ItemsChangedEventArgs results in a 404.
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 42ec4614-4ad0-3167-a191-119e111479f4
* Version Independent ID: 42ec4614-4ad0-3167-a191-119e111479f4
* Content: [ItemContainerGenerator.ItemsChanged Event (Microsoft.UI.Xaml.Controls) - Windows App SDK](https://learn.microsoft.com/en-us/windows/windows-app-sdk/api/winrt/microsoft.ui.xaml.controls.itemcontainergenerator.itemschanged?view=windows-app-sdk-1.1)
* Content Source: [winapps-winrt-build/xml/Microsoft.UI.Xaml.Controls/ItemContainerGenerator.xml](https://github.com/MicrosoftDocs/winapps-winrt-api/blob/docs/winapps-winrt-build/xml/Microsoft.UI.Xaml.Controls/ItemContainerGenerator.xml)
* Product: **reunion**
* Technology: **reunion-reference**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by jwmsft** [comment]
Thanks for reporting this. The link was fixed last year, but we missed closing this issue.
