### ISSUE TITLE
Links to theme definitions do not work/are outdated.

### ISSUE THREAD

**Issue by jeremy-visionaid** [MicrosoftDocs/winapps-winrt-api#90]
Links to themes do not work/are outdated. E.g. 404 for:
https://github.com/microsoft/microsoft-ui-xaml/blob/main/dev/CommonStyles/Common_themeresources_any.xaml

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 246a7bea-2253-d582-1907-e5ea390de42f
* Version Independent ID: 246a7bea-2253-d582-1907-e5ea390de42f
* Content: [ToggleSwitch Class (Microsoft.UI.Xaml.Controls) - Windows App SDK](https://learn.microsoft.com/en-us/windows/windows-app-sdk/api/winrt/microsoft.ui.xaml.controls.toggleswitch?view=windows-app-sdk-1.4&source=docs)
* Content Source: [winapps-winrt-build/xml/Microsoft.UI.Xaml.Controls/ToggleSwitch.xml](https://github.com/MicrosoftDocs/winapps-winrt-api/blob/docs/winapps-winrt-build/xml/Microsoft.UI.Xaml.Controls/ToggleSwitch.xml)
* Product: **reunion**
* Technology: **reunion-reference**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by jwmsft** [comment]
Docs are updated.
