### ISSUE TITLE
Update CharacterReceivedEventArgs.KeyCode docs

### ISSUE THREAD

**Issue by DJm00n** [MicrosoftDocs/winapps-winrt-api#92]
`Microsoft.UI.Input.CharacterReceivedEventArgs.KeyCode` property docs in Windows App SDK contains wrong info that mentions virtual key-code.

Please update it with proper info as in https://github.com/MicrosoftDocs/winrt-api/blob/docs/windows.ui.core/characterreceivedeventargs_keycode.md

See https://github.com/MicrosoftDocs/winrt-api/pull/2428

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: be3c87ee-db1d-8c27-44b1-210a18d5d81e
* Version Independent ID: be3c87ee-db1d-8c27-44b1-210a18d5d81e
* Content: [CharacterReceivedEventArgs.KeyCode Property (Microsoft.UI.Input) - Windows App SDK](https://learn.microsoft.com/en-us/windows/windows-app-sdk/api/winrt/microsoft.ui.input.characterreceivedeventargs.keycode?view=windows-app-sdk-1.4#microsoft-ui-input-characterreceivedeventargs-keycode)
* Content Source: [winapps-winrt-build/xml/Microsoft.UI.Input/CharacterReceivedEventArgs.xml](https://github.com/MicrosoftDocs/winapps-winrt-api/blob/docs/winapps-winrt-build/xml/Microsoft.UI.Input/CharacterReceivedEventArgs.xml)
* Product: **reunion**
* Technology: **reunion-reference**
* GitHub Login: @karl-bridge-microsoft
* Microsoft Alias: **kbridge**

**Comment by DJm00n** [comment]
@Karl-Bridge-Microsoft hi!
Any updates on this?

**Comment by Karl-Bridge-Microsoft** [comment]
Update has been made. Should be live soon.
