### ISSUE TITLE
请问，WebView2要怎么样才能让视频实现在打开声音的情况下自动播放，属性里面没有找打

### ISSUE THREAD

**Issue by ShaoGongBra** [MicrosoftDocs/winapps-winrt-api#93]
[在此处输入反馈]

---
#### 文档详细信息

⚠ *请勿编辑此部分。 learn.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: adc0e98a-e964-728e-125e-3c2ca18e4463
* Version Independent ID: adc0e98a-e964-728e-125e-3c2ca18e4463
* Content: [WebView2 类 (Microsoft.UI.Xaml.Controls) - Windows App SDK](https://learn.microsoft.com/zh-cn/windows/windows-app-sdk/api/winrt/microsoft.ui.xaml.controls.webview2?view=windows-app-sdk-1.4)
* Content Source: [winapps-winrt-build/xml/Microsoft.UI.Xaml.Controls/WebView2.xml](https://github.com/MicrosoftDocs/winapps-winrt-api/blob/docs/winapps-winrt-build/xml/Microsoft.UI.Xaml.Controls/WebView2.xml)
* Product: **reunion**
* Technology: **reunion-reference**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by kqakqakqa** [comment]
可以尝试 [WebView2 浏览器标志](https://learn.microsoft.com/zh-cn/microsoft-edge/webview2/concepts/webview-features-flags?tabs=dotnetcsharp) 设置 `autoplay-policy`
